"""Add BOM and Product Master

Revision ID: c865b07aaf35
Revises: 72679df3ae7e
Create Date: 2026-06-24 16:30:50.036696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c865b07aaf35'
down_revision: Union[str, None] = '72679df3ae7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_master',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_of_measurement', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('bom_master',
    sa.Column('bom_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('bom_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_master.product_id'], ),
    sa.PrimaryKeyConstraint('bom_id'),
    sa.UniqueConstraint('bom_number')
    )
    op.create_table('bom_detail',
    sa.Column('bom_detail_id', sa.UUID(), nullable=False),
    sa.Column('bom_id', sa.UUID(), nullable=False),
    sa.Column('rm_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('scrap_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_master.bom_id'], ),
    sa.ForeignKeyConstraint(['rm_id'], ['rm_master.rm_id'], ),
    sa.PrimaryKeyConstraint('bom_detail_id')
    )
    # op.drop_index('ix_ecfv_entity', table_name='entity_custom_field_values')
    # op.drop_table('entity_custom_field_values')
    # op.drop_table('entity_custom_fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_custom_fields',
    sa.Column('field_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('field_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('field_label', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('dropdown_options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_visible_in_list', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('field_id', name='entity_custom_fields_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('entity_custom_field_values',
    sa.Column('value_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['entity_custom_fields.field_id'], name='entity_custom_field_values_field_id_fkey'),
    sa.PrimaryKeyConstraint('value_id', name='entity_custom_field_values_pkey')
    )
    op.create_index('ix_ecfv_entity', 'entity_custom_field_values', ['entity_type', 'entity_id'], unique=False)
    op.drop_table('bom_detail')
    op.drop_table('bom_master')
    op.drop_table('product_master')
    # ### end Alembic commands ###
