"""Add delivery mode

Revision ID: fb3c88bb8890
Revises: 695569b912d2
Create Date: 2026-06-26 13:40:09.923197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3c88bb8890'
down_revision: Union[str, None] = '695569b912d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asn_log', sa.Column('delivery_mode', sa.String(length=50), nullable=False))
    op.add_column('asn_log', sa.Column('courier_name', sa.String(length=100), nullable=True))
    op.add_column('asn_log', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asn_log', 'tracking_number')
    op.drop_column('asn_log', 'courier_name')
    op.drop_column('asn_log', 'delivery_mode')
    # ### end Alembic commands ###
